name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

env:
  app_name: box64
  app_repo: ptitSeb/box64
  
jobs:
  check-binaries:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get-version.outputs.app_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Get Version
        id: get-version
        run: |
          app_version=$(curl -s "https://api.github.com/repos/${{ env.app_repo }}/releases/latest" | jq -r .tag_name)
          if [ -z "${app_version}" ] || [ "${app_version}" == "null" ]; then
            echo "Failed to get version"
            exit 1
          fi
          
          echo "app_version=${app_version}" >> $GITHUB_ENV
          echo "app_version=${app_version}" >> $GITHUB_OUTPUT
          echo ""
          echo "========== Build Args =========="
          echo "app_version=${app_version}"

      - name: Check Release
        id: check-release
        run: |
          gh release view ${app_version} -R ${{ github.repository }} >/dev/null 2>&1 || echo "create=1" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        if : steps.check-release.outputs.create == '1'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Release ${app_version}" || true
          git tag ${app_version}
          git push origin ${app_version}  || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if : steps.check-release.outputs.create == '1'
        run: |
          gh release create ${app_version} -R ${{ github.repository }} --title ${app_version} --notes "**Full Changelog**: [${app_version}](https://github.com/${{ env.app_repo }}/releases/tag/${app_version})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-deb:
    runs-on: ubuntu-latest
    needs: check-binaries
    env:
      app_version: ${{ needs.check-binaries.outputs.app_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.app_version }}
      
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Check Release
        id: create-binaries
        run: |
          gh release view ${{ env.app_version }} -R ${{ github.repository }} | grep ${{ env.app_name }}_.*_loong64.deb >/dev/null 2>&1 || echo "create=1" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Binaries
        if : steps.create-binaries.outputs.create == '1'
        run: |
          docker buildx build --platform linux/loong64 --build-arg VERSION=${{ env.app_version }} -t ${{ env.app_name }}-debian-loong64:${{ env.app_version }} debian --load

      - name: Upgrade Release
        if : steps.create-binaries.outputs.create == '1'
        run: |
          docker run --rm -v $(pwd)/dist:/dist ${{ env.app_name }}-debian-loong64:${{ env.app_version }}
          ls -al dist
          gh release upload ${{ env.app_version }} -R ${{ github.repository }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-lib:
    runs-on: ubuntu-latest
    needs: check-binaries
    env:
      app_version: ${{ needs.check-binaries.outputs.app_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.app_version }}
      
      - uses: docker/setup-buildx-action@v3

      - name: Check Release
        id: create-binaries
        run: |
          gh release view ${{ env.app_version }} -R ${{ github.repository }} | grep ${{ env.app_name }}-bundle-x86-libs.tar.gz >/dev/null 2>&1 || echo "create=1" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Binaries
        if : steps.create-binaries.outputs.create == '1'
        run: |
          docker buildx build --build-arg VERSION=${{ env.app_version }} -t ${{ env.app_name }}-libs-loong64:${{ env.app_version }} libs --load

      - name: Upgrade Release
        if : steps.create-binaries.outputs.create == '1'
        run: |
          docker run --rm -v $(pwd)/dist:/dist ${{ env.app_name }}-libs-loong64:${{ env.app_version }}
          ls -al dist
          gh release upload ${{ env.app_version }} -R ${{ github.repository }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-cross:
    runs-on: ubuntu-latest
    needs: check-binaries
    env:
      app_version: ${{ needs.check-binaries.outputs.app_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.app_version }}
      
      - uses: docker/setup-buildx-action@v3

      - name: Check Release
        id: create-binaries
        run: |
          gh release view ${{ env.app_version }} -R ${{ github.repository }} | grep ${{ env.app_name }}-linux-loong64.tar.gz >/dev/null 2>&1 || echo "create=1" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Binaries
        if : steps.create-binaries.outputs.create == '1'
        run: |
          docker buildx build --build-arg VERSION=${{ env.app_version }} -t ${{ env.app_name }}-cross-loong64:${{ env.app_version }} cross-compiler/loong64 --load

      - name: Upgrade Release
        if : steps.create-binaries.outputs.create == '1'
        run: |
          docker run --rm -v $(pwd)/dist:/dist ${{ env.app_name }}-cross-loong64:${{ env.app_version }}
          ls -al dist
          gh release upload ${{ env.app_version }} -R ${{ github.repository }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}